Import NumPy :

Once NumPy is installed , imported it in your application by adding the import keyword . It is usually imported as np allias.

In [325]:
import numpy as np 
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


Checking NumPy version :

In [326]:
print(np.__version__)

1.26.3


1 . Basic Array Functions

* Dimension in Arrays -> A dimension is one level of array depth (nested arrays).

* 0-D Arrays -> 0-D arrays or scalars , are the elements in an array . Each value in an array is a 0-D array.

In [327]:
arr = np.array(45)
print(arr)

45


* 1-D Arrays ->An arrays as its elements is called uni-dimensional or 1-D array. These are most common and basic arrays.

In [328]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


* 2-D Arrays -> An arrays that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.
  

In [329]:
arr = np.array([[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]])
print(arr)

[[10 20 30 40 50]
 [10 20 30 40 50]]


* 3-D Arrays -> A 3-D array is a data structure that stores information in three dimensions, forming a cube-like structure for complex data representation.

In [330]:
arr = np.array([[[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]],[[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]]])
print(arr)

[[[10 20 30 40 50]
  [10 20 30 40 50]]

 [[10 20 30 40 50]
  [10 20 30 40 50]]]


Number of Dimension:

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimension do the arrays have

In [331]:
a = np.array(10)
b = np.array([10, 20, 30, 40, 50])
c = np.array([[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]])
d = np.array([[[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]],[[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


2. NumPy Array Indexing

   Access Array elements:

Array Indexing is the same as ascending an array element . The indexes in NumPy start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [332]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

arr = np.array([[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]])
print(arr[0, 2])

arr = np.array([[[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]],[[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]]])
print(arr[0, 1, 4])

10
30
50


Negative Indexing :
Use negative indexing to access an array from the end

In [333]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:-1])

[20 30 40]


3. NumPy Array Slicing 

Slicing in Python means taking elements from one given index to another given index.
The Syntax is : [start:end:step]
By default start is considered to be 0 ,  the end is considered to be length of the array , step is 1 .

In [334]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4:2])

[20 40]


In [335]:
print('First 3 elements', arr[:3])

First 3 elements [10 20 30]


Negative Slicing:

Use the minus operator to refer t and index from the end

In [336]:
print('Last 3 elements', arr[-3:])

Last 3 elements [30 40 50]


4. NumPy Data Types

NumPy has one extra data types and refer to data types with one character , like i for integers , u for unsigned integers etc.

i - integer ,
b - boolean  , 
u - unsigned integer ,
f - float  ,
c - complex float ,
m - timedelta ,
M - datetime ,
O - Object  ,
s - String



* Checking the Data Types of an Array

The NumPy array object has a property called dtype that returns the datatype of the array.

In [337]:
arr = np.array([10, 20, 30, 40, 50])
print(arr.dtype)

int32


* Creating Array with Defined Data Type
  
  We use array function to create arrays . It can take an optional argument dtype , that allows us to define the expected data type of the array elemnts

In [338]:
arr = np.array([10, 20, 30, 40, 50] , dtype='float')
print(arr)
print(arr.dtype)

[10. 20. 30. 40. 50.]
float64


5. NumPy Array Copy vs View

* Copy :
  It owns the data and any change made to the copy will not affect original array , and any changes made to the original array will not affect the copy

In [339]:
arr = np.array([10, 20, 30, 40, 50])
x = arr.copy()
arr[0]=1000
print(arr)
print(x)

[1000   20   30   40   50]
[10 20 30 40 50]


View :
It does not own the data and any changes made to the view will affect the original array.

In [340]:
arr = np.array([10, 20, 30, 40, 50])
x = arr.view()
arr[0]=1000
print(arr)
print(x)

[1000   20   30   40   50]
[1000   20   30   40   50]


6. NumPy Array Shape

* Shape :
  The shape of an array is the number of elements in each dimension.

In [341]:
arr = np.array([[10, 20, 30, 40, 50],[10, 20, 30, 40, 50]])
print(arr.shape)

(2, 5)


7. NumPy Joining Array

Joining means putting contents of two or more arrays in a single array.

In [342]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60,70,80,90,100])
arr = np.concatenate((arr1, arr2))
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


* Joining Array using Stack Function:
  Stacking is same as concatenation , the only difference is that stacking is done along a new axis.

In [343]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60,70,80,90,100])
arr = np.stack((arr1, arr2),axis=1)
print(arr)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


8. NumPy Sorting Arrays

* Sorting Arrays :
  Sorting means putting elements in an ordered sequence.
  Ordered sequence is any sequence that has an order corresponding to elements , like numeric or alphabetical , ascending or descending.
  The NumPy ndarray object has a function called sort() , that will sort a specified array.

In [344]:
arr = np.array([100, 2, 3000, 4, 51])
print(np.sort(arr))

[   2    4   51  100 3000]
